SLING-11912 - Empty configuration in ServiceUserMapperImpl's Required…
apache/sling-org-apache-sling-serviceusermapper pull request #8
Opened 2023-06-21 08:14 UTC by sagarmiglani

… Principal/User validators results in 503

This PR is filtering out the empty values provided in `required.user.validators` and`required.principal.validators`.
Empty values present in these configuration make sling request to return:
`HTTP ERROR 503 ServletResolver service missing, cannot service requests`
For more information, please have a look at SLING-11912

2023-06-21 08:29 UTC, sagarmiglani commented
@anchela @kwin @cziegeler Could you please help with the review? Thanks

2023-06-21 10:02 UTC, kwin requested changes

2023-06-21 10:02 UTC, kwin commented on src/main/java/org/apache/sling/serviceusermapping/impl/ServiceUserMapperImpl.java
> +    private List<String> filterEmptyStringValues(String[] arr) {
I would add the null check on the array in here instead of outside this method.

2023-06-21 10:02 UTC, kwin commented on src/main/java/org/apache/sling/serviceusermapping/impl/ServiceUserMapperImpl.java
> +        return Arrays.stream(arr).filter(p -> !p.trim().isEmpty()).collect(Collectors.toList());
I would at least log that empty values are disregarded.

2023-06-21 17:34 UTC, anchela reviewed
hi @sagarmiglani , the changes look reasonable to me, but the original code has been added by @karlpauls. since the ServiceUserMapper is easily prone to regressions that result in failing AEM startup, i would recommend to also request a review from karl. he definitely know this part very of Sling better than me.

2023-07-20 05:02 UTC, cziegeler commented
@sagarmiglani Could you maybe add the logging as requested by @kwin ?

2023-07-20 05:52 UTC, cziegeler approved these changes

2023-07-20 05:55 UTC, merged